// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.egso.comms.pis.types;


public class Message {
    protected org.egso.comms.pis.types.Header header;
    protected javax.xml.soap.SOAPElement body;
    
    public Message() {
    }
    
    public Message(org.egso.comms.pis.types.Header header, javax.xml.soap.SOAPElement body) {
        this.header = header;
        this.body = body;
    }
    
    public org.egso.comms.pis.types.Header getHeader() {
        return header;
    }
    
    public void setHeader(org.egso.comms.pis.types.Header header) {
        this.header = header;
    }
    
    public javax.xml.soap.SOAPElement getBody() {
        return body;
    }
    
    public void setBody(javax.xml.soap.SOAPElement body) {
        this.body = body;
    }
}
