<xsl:stylesheet version="1.0" 
xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:output method="xml"/>
 
<xsl:template match="/TimeTable">
 <VOTABLE version='1.1'>
 <DESCRIPTION>
        Time Table generated by AMDA @ CDPP;
        Description: <xsl:value-of select="Chain"/>; 
        Source: <xsl:value-of select="Source"/>;
        Creation Date :  <xsl:value-of select="Created"/>; 
 </DESCRIPTION>
<RESOURCE>
<DESCRIPTION>
        AMDA @ CDPP
</DESCRIPTION>
<TABLE>
<FIELD datatype='char' name='Start Time' ID='TimeIntervalStart' ucd='time.start'>
    <DESCRIPTION>time tag for beginning of interval</DESCRIPTION>
</FIELD>
<FIELD datatype='char' name='Stop Time' ID='TimeIntervalStop' ucd='time.stop'>
    <DESCRIPTION>time tag for end of interval</DESCRIPTION>
</FIELD>
<DATA>
  <TABLEDATA> 
  <xsl:for-each select="Interval">
    <TR>
       <TD><xsl:value-of select="Start"/></TD>
       <TD><xsl:value-of select="Stop"/></TD> 
    </TR> 
    </xsl:for-each>
    </TABLEDATA>
   </DATA>
   </TABLE>
  </RESOURCE>    
 </VOTABLE>
</xsl:template>
</xsl:stylesheet>
