<xsl:stylesheet version="1.0" 
xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:output method="xml"/>
<xsl:template match="/MDES"> 

 <VOTABLE version='1.1' xmlns="http://www.ivoa.net/xml/VOTable/v1.1">
 <DESCRIPTION>Time Table generated by AMDA @ CDPP</DESCRIPTION>
  <xsl:for-each select="TimeTable">
  <xsl:variable name="tableName">  
     <xsl:value-of select="@Name"/>
  </xsl:variable>
  <RESOURCE>
  <DESCRIPTION>
       Time Table generated by AMDA @ CDPP
    <!--    Description: <xsl:value-of select="Chain"/>; 
        Source: <xsl:value-of select="Source"/>;
        Creation Date :  <xsl:value-of select="Created"/>; -->
  </DESCRIPTION>
  <INFO name = "CreationDate"> 
    <xsl:attribute name="value">
	<xsl:value-of select="Creation_Date"/>
    </xsl:attribute>
  </INFO>
  <INFO name = "Instument"> 
    <xsl:attribute name="value">
	<xsl:value-of select="Instrument"/>
    </xsl:attribute>
  </INFO>
  <INFO name = "SearchFunction"> 
    <xsl:attribute name="value">
	<xsl:value-of select="@Name"/>
    </xsl:attribute>
  </INFO>
  <INFO name = "FunctionDescription"> 
    <xsl:attribute name="value">
	<xsl:value-of select="Function_Description"/>
    </xsl:attribute>
  </INFO>
  <INFO name = "FunctionDefinition"> 
    <xsl:attribute name="value">
	<xsl:value-of select="newChain"/>
    </xsl:attribute>
  </INFO>
  <INFO name = "TIME_RANGE"> 
    <xsl:attribute name="value">
	<xsl:value-of select="TIME_RANGE"/>
    </xsl:attribute>
  </INFO>
  
  <TABLE name = "{@Name}">
  <FIELD arraysize='*' datatype='char' name='time_start' ID='TimeIntervalStart' ucd='time.start' xtype='iso8601' utype='helio:time_period.time_start'>
    <DESCRIPTION>time tag for beginning of interval</DESCRIPTION>
  </FIELD>
  <FIELD arraysize='*' datatype='char' name='time_end' ID='TimeIntervalStop' ucd='time.end' xtype='iso8601' utype='helio:time_period.time_end'>
    <DESCRIPTION>time tag for end of interval</DESCRIPTION>
  </FIELD>
  <DATA>
  <TABLEDATA> 
  <xsl:for-each select="Interval">
    <TR>
       <TD><xsl:value-of select="Start"/></TD>
       <TD><xsl:value-of select="Stop"/></TD> 
    </TR> 
    </xsl:for-each>
    </TABLEDATA>
   </DATA>
   </TABLE>
  </RESOURCE> 
</xsl:for-each>   
 </VOTABLE>
</xsl:template>
</xsl:stylesheet>
