
package eu.heliovo.sms;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "smsFault", targetNamespace = "http://sms.heliovo.eu/")
public class SmsFault_Exception
    extends Exception
{

    /**
	 * generated serialVersionUID
	 */
	private static final long serialVersionUID = -8543770369895601895L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SmsFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public SmsFault_Exception(String message, SmsFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public SmsFault_Exception(String message, SmsFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: eu.heliovo.sms.SmsFault
     */
    public SmsFault getFaultInfo() {
        return faultInfo;
    }

}
