
package eu.heliovo.sms;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SMSService", targetNamespace = "http://sms.heliovo.eu/", wsdlLocation = "file:/C:/Program%20Files/Apache/Tomcat%206.0/webapps/helio-sms-0.0.1-SNAPSHOT/WEB-INF/wsdl/SMSService.wsdl")
public class SMSService
    extends Service
{

    private final static URL SMSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(eu.heliovo.sms.SMSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = eu.heliovo.sms.SMSService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Program%20Files/Apache/Tomcat%206.0/webapps/helio-sms-0.0.1-SNAPSHOT/WEB-INF/wsdl/SMSService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Program%20Files/Apache/Tomcat%206.0/webapps/helio-sms-0.0.1-SNAPSHOT/WEB-INF/wsdl/SMSService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SMSSERVICE_WSDL_LOCATION = url;
    }

    public SMSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SMSService() {
        super(SMSSERVICE_WSDL_LOCATION, new QName("http://sms.heliovo.eu/", "SMSService"));
    }

    /**
     * 
     * @return
     *     returns SMS
     */
    @WebEndpoint(name = "SMSPort")
    public SMS getSMSPort() {
        return super.getPort(new QName("http://sms.heliovo.eu/", "SMSPort"), SMS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SMS
     */
    @WebEndpoint(name = "SMSPort")
    public SMS getSMSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sms.heliovo.eu/", "SMSPort"), SMS.class, features);
    }

}
