// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.egso.comms.log.wsdl;

import javax.xml.rpc.ServiceException;

public interface Logging_Service extends javax.xml.rpc.Service {
    public org.egso.comms.log.wsdl.Logging_PortType getLoggingPort() throws ServiceException;
}
