// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.egso.comms.log.types;


public class Event {
    protected java.lang.String id;
    protected java.lang.String logId;
    protected java.lang.String logger;
    protected java.lang.String level;
    protected java.lang.String thread;
    protected long timeAppended;
    protected java.lang.String message;
    protected java.lang.String ndc;
    protected org.egso.comms.log.types.Throwable throwable;
    protected org.egso.comms.log.types.Location location;
    
    public Event() {
    }
    
    public Event(java.lang.String id, java.lang.String logId, java.lang.String logger, java.lang.String level, java.lang.String thread, long timeAppended, java.lang.String message, java.lang.String ndc, org.egso.comms.log.types.Throwable throwable, org.egso.comms.log.types.Location location) {
        this.id = id;
        this.logId = logId;
        this.logger = logger;
        this.level = level;
        this.thread = thread;
        this.timeAppended = timeAppended;
        this.message = message;
        this.ndc = ndc;
        this.throwable = throwable;
        this.location = location;
    }
    
    public java.lang.String getId() {
        return id;
    }
    
    public void setId(java.lang.String id) {
        this.id = id;
    }
    
    public java.lang.String getLogId() {
        return logId;
    }
    
    public void setLogId(java.lang.String logId) {
        this.logId = logId;
    }
    
    public java.lang.String getLogger() {
        return logger;
    }
    
    public void setLogger(java.lang.String logger) {
        this.logger = logger;
    }
    
    public java.lang.String getLevel() {
        return level;
    }
    
    public void setLevel(java.lang.String level) {
        this.level = level;
    }
    
    public java.lang.String getThread() {
        return thread;
    }
    
    public void setThread(java.lang.String thread) {
        this.thread = thread;
    }
    
    public long getTimeAppended() {
        return timeAppended;
    }
    
    public void setTimeAppended(long timeAppended) {
        this.timeAppended = timeAppended;
    }
    
    public java.lang.String getMessage() {
        return message;
    }
    
    public void setMessage(java.lang.String message) {
        this.message = message;
    }
    
    public java.lang.String getNdc() {
        return ndc;
    }
    
    public void setNdc(java.lang.String ndc) {
        this.ndc = ndc;
    }
    
    public org.egso.comms.log.types.Throwable getThrowable() {
        return throwable;
    }
    
    public void setThrowable(org.egso.comms.log.types.Throwable throwable) {
        this.throwable = throwable;
    }
    
    public org.egso.comms.log.types.Location getLocation() {
        return location;
    }
    
    public void setLocation(org.egso.comms.log.types.Location location) {
        this.location = location;
    }
}
