// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.egso.comms.log.types;


public class EventList {
    protected org.egso.comms.log.types.Event[] events;
    
    public EventList() {
    }
    
    public EventList(org.egso.comms.log.types.Event[] events) {
        this.events = events;
    }
    
    public org.egso.comms.log.types.Event[] getEvents() {
        return events;
    }
    
    public void setEvents(org.egso.comms.log.types.Event[] events) {
        this.events = events;
    }
}
