// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.egso.comms.log.types;


public class Location {
    protected java.lang.String type;
    protected java.lang.String method;
    protected java.lang.String file;
    protected java.lang.Integer line;
    
    public Location() {
    }
    
    public Location(java.lang.String type, java.lang.String method, java.lang.String file, java.lang.Integer line) {
        this.type = type;
        this.method = method;
        this.file = file;
        this.line = line;
    }
    
    public java.lang.String getType() {
        return type;
    }
    
    public void setType(java.lang.String type) {
        this.type = type;
    }
    
    public java.lang.String getMethod() {
        return method;
    }
    
    public void setMethod(java.lang.String method) {
        this.method = method;
    }
    
    public java.lang.String getFile() {
        return file;
    }
    
    public void setFile(java.lang.String file) {
        this.file = file;
    }
    
    public java.lang.Integer getLine() {
        return line;
    }
    
    public void setLine(java.lang.Integer line) {
        this.line = line;
    }
}
