// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.egso.comms.log.types;


public class Log {
    protected java.lang.String id;
    protected java.lang.String ownerId;
    protected java.lang.String name;
    protected long timeCreated;
    
    public Log() {
    }
    
    public Log(java.lang.String id, java.lang.String ownerId, java.lang.String name, long timeCreated) {
        this.id = id;
        this.ownerId = ownerId;
        this.name = name;
        this.timeCreated = timeCreated;
    }
    
    public java.lang.String getId() {
        return id;
    }
    
    public void setId(java.lang.String id) {
        this.id = id;
    }
    
    public java.lang.String getOwnerId() {
        return ownerId;
    }
    
    public void setOwnerId(java.lang.String ownerId) {
        this.ownerId = ownerId;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public long getTimeCreated() {
        return timeCreated;
    }
    
    public void setTimeCreated(long timeCreated) {
        this.timeCreated = timeCreated;
    }
}
