
package ch.i4ds.helio.core;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "FrontendFacadeService", targetNamespace = "http://core.helio.i4ds.ch/", wsdlLocation = "http://helio-dev.i4ds.technik.fhnw.ch:8080/core/services/frontend?wsdl")
public class FrontendFacadeService
    extends Service
{

    private final static URL FRONTENDFACADESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ch.i4ds.helio.core.FrontendFacadeService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ch.i4ds.helio.core.FrontendFacadeService.class.getResource(".");
            url = new URL(baseUrl, "http://helio-dev.i4ds.technik.fhnw.ch:8080/core/services/frontend?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://helio-dev.i4ds.technik.fhnw.ch:8080/core/services/frontend?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FRONTENDFACADESERVICE_WSDL_LOCATION = url;
    }

    public FrontendFacadeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FrontendFacadeService() {
        super(FRONTENDFACADESERVICE_WSDL_LOCATION, new QName("http://core.helio.i4ds.ch/", "FrontendFacadeService"));
    }

    /**
     * 
     * @return
     *     returns FrontendFacade
     */
    @WebEndpoint(name = "FrontendFacadePort")
    public FrontendFacade getFrontendFacadePort() {
        return super.getPort(new QName("http://core.helio.i4ds.ch/", "FrontendFacadePort"), FrontendFacade.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FrontendFacade
     */
    @WebEndpoint(name = "FrontendFacadePort")
    public FrontendFacade getFrontendFacadePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://core.helio.i4ds.ch/", "FrontendFacadePort"), FrontendFacade.class, features);
    }

}
