
package eu.heliovo.workflow.clients.dpas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "QueryServiceService", targetNamespace = "http://controller.dpas.helio.i4ds.ie", wsdlLocation = "http://helio.i4ds.technik.fhnw.ch:8080/HelioDPAS-R1/services/QueryService?wsdl")
public class QueryServiceService
    extends Service
{

    private final static URL QUERYSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException QUERYSERVICESERVICE_EXCEPTION;
    private final static QName QUERYSERVICESERVICE_QNAME = new QName("http://controller.dpas.helio.i4ds.ie", "QueryServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://helio.i4ds.technik.fhnw.ch:8080/HelioDPAS-R1/services/QueryService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QUERYSERVICESERVICE_WSDL_LOCATION = url;
        QUERYSERVICESERVICE_EXCEPTION = e;
    }

    public QueryServiceService() {
        super(__getWsdlLocation(), QUERYSERVICESERVICE_QNAME);
    }

    public QueryServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUERYSERVICESERVICE_QNAME, features);
    }

    public QueryServiceService(URL wsdlLocation) {
        super(wsdlLocation, QUERYSERVICESERVICE_QNAME);
    }

    public QueryServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUERYSERVICESERVICE_QNAME, features);
    }

    public QueryServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns QueryService
     */
    @WebEndpoint(name = "QueryService")
    public QueryService getQueryService() {
        return super.getPort(new QName("http://controller.dpas.helio.i4ds.ie", "QueryService"), QueryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryService
     */
    @WebEndpoint(name = "QueryService")
    public QueryService getQueryService(WebServiceFeature... features) {
        return super.getPort(new QName("http://controller.dpas.helio.i4ds.ie", "QueryService"), QueryService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUERYSERVICESERVICE_EXCEPTION!= null) {
            throw QUERYSERVICESERVICE_EXCEPTION;
        }
        return QUERYSERVICESERVICE_WSDL_LOCATION;
    }

}
