// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.egso.comms.pis.wsdl;

import javax.xml.namespace.QName;
import javax.xml.rpc.JAXRPCException;

import com.sun.xml.rpc.client.HandlerChainImpl;
import com.sun.xml.rpc.client.ServiceExceptionImpl;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class PIS_Service_Impl extends com.sun.xml.rpc.client.BasicService implements PIS_Service {
    private static final QName serviceName = new QName("urn:org.egso.comms/pis/wsdl/PIS", "PIS");
    private static final QName ns1_PISPort_QNAME = new QName("urn:org.egso.comms/pis/wsdl/PIS", "PISPort");
    private static final Class PIS_PortType_PortClass = org.egso.comms.pis.wsdl.PIS_PortType.class;
    
    public PIS_Service_Impl() {
        super(serviceName, new QName[] {
                        ns1_PISPort_QNAME
                    },
            new org.egso.comms.pis.wsdl.PIS_Service_SerializerRegistry().getRegistry());
        
    }
    
    public java.rmi.Remote getPort(QName portName, Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (portName.equals(ns1_PISPort_QNAME) &&
                serviceDefInterface.equals(PIS_PortType_PortClass)) {
                return getPISPort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(portName, serviceDefInterface);
    }
    
    public java.rmi.Remote getPort(Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (serviceDefInterface.equals(PIS_PortType_PortClass)) {
                return getPISPort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(serviceDefInterface);
    }
    
    public org.egso.comms.pis.wsdl.PIS_PortType getPISPort() {
        String[] roles = new String[] {};
        HandlerChainImpl handlerChain = new HandlerChainImpl(getHandlerRegistry().getHandlerChain(ns1_PISPort_QNAME));
        handlerChain.setRoles(roles);
        org.egso.comms.pis.wsdl.PIS_PortType_Stub stub = new org.egso.comms.pis.wsdl.PIS_PortType_Stub(handlerChain);
        try {
            stub._initialize(super.internalTypeRegistry);
        } catch (JAXRPCException e) {
            throw e;
        } catch (Exception e) {
            throw new JAXRPCException(e.getMessage(), e);
        }
        return stub;
    }
}
