/*
Copyright (c) 2009 Sebastian Hennebrueder, http://www.laliluna.de

Licensed under the Open Source Robin Hood License, Version 0.1 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.laliluna.de/open-source-robin-hood-license.html

Unless required by applicable law or agreed to in writing, software distributed under the License
is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied,
without even the implied warranty of  FITNESS FOR A PARTICULAR PURPOSE.
See the License for the specific language governing permissions and limitations under the License.
 */

//package de.laliluna.date;

package ips;

import java.util.Arrays;
import java.util.List;


/**
 * Helper class to convert the enum {@code TimeZone} to Java's {@code java.util.TimeZone} and back
 */
public class TimeZoneUtil {

  public static final List<TimeZone> zones = Arrays
          .asList(TimeZone.ETC_GMT12, TimeZone.ETC_GMT11, TimeZone.MIT, TimeZone.PACIFIC_APIA, TimeZone.PACIFIC_MIDWAY,
                  TimeZone.PACIFIC_NIUE, TimeZone.PACIFIC_PAGO_PAGO, TimeZone.PACIFIC_SAMOA, TimeZone.US_SAMOA,
                  TimeZone.AMERICA_ADAK, TimeZone.AMERICA_ATKA, TimeZone.ETC_GMT10, TimeZone.HST,
                  TimeZone.PACIFIC_FAKAOFO, TimeZone.PACIFIC_HONOLULU, TimeZone.PACIFIC_JOHNSTON,
                  TimeZone.PACIFIC_RAROTONGA, TimeZone.PACIFIC_TAHITI, TimeZone.SYSTEMV_HST10, TimeZone.US_ALEUTIAN,
                  TimeZone.US_HAWAII, TimeZone.PACIFIC_MARQUESAS, TimeZone.AST, TimeZone.AMERICA_ANCHORAGE,
                  TimeZone.AMERICA_JUNEAU, TimeZone.AMERICA_NOME, TimeZone.AMERICA_YAKUTAT, TimeZone.ETC_GMT9,
                  TimeZone.PACIFIC_GAMBIER, TimeZone.SYSTEMV_YST9, TimeZone.SYSTEMV_YST9YDT, TimeZone.US_ALASKA,
                  TimeZone.AMERICA_DAWSON, TimeZone.AMERICA_ENSENADA, TimeZone.AMERICA_LOS_ANGELES,
                  TimeZone.AMERICA_TIJUANA, TimeZone.AMERICA_VANCOUVER, TimeZone.AMERICA_WHITEHORSE,
                  TimeZone.CANADA_PACIFIC, TimeZone.CANADA_YUKON, TimeZone.ETC_GMT8, TimeZone.MEXICO_BAJANORTE,
                  TimeZone.PST, TimeZone.PST8PDT, TimeZone.PACIFIC_PITCAIRN, TimeZone.SYSTEMV_PST8,
                  TimeZone.SYSTEMV_PST8PDT, TimeZone.US_PACIFIC, TimeZone.US_PACIFIC_NEW, TimeZone.AMERICA_BOISE,
                  TimeZone.AMERICA_CAMBRIDGE_BAY, TimeZone.AMERICA_CHIHUAHUA, TimeZone.AMERICA_DAWSON_CREEK,
                  TimeZone.AMERICA_DENVER, TimeZone.AMERICA_EDMONTON, TimeZone.AMERICA_HERMOSILLO,
                  TimeZone.AMERICA_INUVIK, TimeZone.AMERICA_MAZATLAN, TimeZone.AMERICA_PHOENIX,
                  TimeZone.AMERICA_SHIPROCK, TimeZone.AMERICA_YELLOWKNIFE, TimeZone.CANADA_MOUNTAIN, TimeZone.ETC_GMT7,
                  TimeZone.MST, TimeZone.MST7MDT, TimeZone.MEXICO_BAJASUR, TimeZone.NAVAJO, TimeZone.PNT,
                  TimeZone.SYSTEMV_MST7, TimeZone.SYSTEMV_MST7MDT, TimeZone.US_ARIZONA, TimeZone.US_MOUNTAIN,
                  TimeZone.AMERICA_BELIZE, TimeZone.AMERICA_CANCUN, TimeZone.AMERICA_CHICAGO,
                  TimeZone.AMERICA_COSTA_RICA, TimeZone.AMERICA_EL_SALVADOR, TimeZone.AMERICA_GUATEMALA,
                  TimeZone.AMERICA_INDIANA_KNOX, TimeZone.AMERICA_INDIANA_TELL_CITY, TimeZone.AMERICA_KNOX_IN,
                  TimeZone.AMERICA_MANAGUA, TimeZone.AMERICA_MENOMINEE, TimeZone.AMERICA_MERIDA,
                  TimeZone.AMERICA_MEXICO_CITY, TimeZone.AMERICA_MONTERREY, TimeZone.AMERICA_NORTH_DAKOTA_CENTER,
                  TimeZone.AMERICA_NORTH_DAKOTA_NEW_SALEM, TimeZone.AMERICA_RAINY_RIVER, TimeZone.AMERICA_RANKIN_INLET,
                  TimeZone.AMERICA_REGINA, TimeZone.AMERICA_SWIFT_CURRENT, TimeZone.AMERICA_TEGUCIGALPA,
                  TimeZone.AMERICA_WINNIPEG, TimeZone.CST, TimeZone.CST6CDT, TimeZone.CANADA_CENTRAL,
                  TimeZone.CANADA_EAST_SASKATCHEWAN, TimeZone.CANADA_SASKATCHEWAN, TimeZone.CHILE_EASTERISLAND,
                  TimeZone.ETC_GMT6, TimeZone.MEXICO_GENERAL, TimeZone.PACIFIC_EASTER, TimeZone.PACIFIC_GALAPAGOS,
                  TimeZone.SYSTEMV_CST6, TimeZone.SYSTEMV_CST6CDT, TimeZone.US_CENTRAL, TimeZone.US_INDIANA_STARKE,
                  TimeZone.AMERICA_ATIKOKAN, TimeZone.AMERICA_BOGOTA, TimeZone.AMERICA_CAYMAN,
                  TimeZone.AMERICA_CORAL_HARBOUR, TimeZone.AMERICA_DETROIT, TimeZone.AMERICA_EIRUNEPE,
                  TimeZone.AMERICA_FORT_WAYNE, TimeZone.AMERICA_GRAND_TURK, TimeZone.AMERICA_GUAYAQUIL,
                  TimeZone.AMERICA_HAVANA, TimeZone.AMERICA_INDIANA_INDIANAPOLIS, TimeZone.AMERICA_INDIANA_MARENGO,
                  TimeZone.AMERICA_INDIANA_PETERSBURG, TimeZone.AMERICA_INDIANA_VEVAY,
                  TimeZone.AMERICA_INDIANA_VINCENNES, TimeZone.AMERICA_INDIANA_WINAMAC, TimeZone.AMERICA_INDIANAPOLIS,
                  TimeZone.AMERICA_IQALUIT, TimeZone.AMERICA_JAMAICA, TimeZone.AMERICA_KENTUCKY_LOUISVILLE,
                  TimeZone.AMERICA_KENTUCKY_MONTICELLO, TimeZone.AMERICA_LIMA, TimeZone.AMERICA_LOUISVILLE,
                  TimeZone.AMERICA_MONTREAL, TimeZone.AMERICA_NASSAU, TimeZone.AMERICA_NEW_YORK,
                  TimeZone.AMERICA_NIPIGON, TimeZone.AMERICA_PANAMA, TimeZone.AMERICA_PANGNIRTUNG,
                  TimeZone.AMERICA_PORT_AU_PRINCE, TimeZone.AMERICA_PORTO_ACRE, TimeZone.AMERICA_RESOLUTE,
                  TimeZone.AMERICA_RIO_BRANCO, TimeZone.AMERICA_THUNDER_BAY, TimeZone.AMERICA_TORONTO,
                  TimeZone.BRAZIL_ACRE, TimeZone.CANADA_EASTERN, TimeZone.CUBA, TimeZone.EST, TimeZone.EST5EDT,
                  TimeZone.ETC_GMT5, TimeZone.IET, TimeZone.JAMAICA, TimeZone.SYSTEMV_EST5, TimeZone.SYSTEMV_EST5EDT,
                  TimeZone.US_EAST_INDIANA, TimeZone.US_EASTERN, TimeZone.US_MICHIGAN, TimeZone.AMERICA_CARACAS,
                  TimeZone.AMERICA_ANGUILLA, TimeZone.AMERICA_ANTIGUA, TimeZone.AMERICA_ARUBA,
                  TimeZone.AMERICA_ASUNCION, TimeZone.AMERICA_BARBADOS, TimeZone.AMERICA_BLANC_SABLON,
                  TimeZone.AMERICA_BOA_VISTA, TimeZone.AMERICA_CAMPO_GRANDE, TimeZone.AMERICA_CUIABA,
                  TimeZone.AMERICA_CURACAO, TimeZone.AMERICA_DOMINICA, TimeZone.AMERICA_GLACE_BAY,
                  TimeZone.AMERICA_GOOSE_BAY, TimeZone.AMERICA_GRENADA, TimeZone.AMERICA_GUADELOUPE,
                  TimeZone.AMERICA_GUYANA, TimeZone.AMERICA_HALIFAX, TimeZone.AMERICA_LA_PAZ, TimeZone.AMERICA_MANAUS,
                  TimeZone.AMERICA_MARIGOT, TimeZone.AMERICA_MARTINIQUE, TimeZone.AMERICA_MONCTON,
                  TimeZone.AMERICA_MONTSERRAT, TimeZone.AMERICA_PORT_OF_SPAIN, TimeZone.AMERICA_PORTO_VELHO,
                  TimeZone.AMERICA_PUERTO_RICO, TimeZone.AMERICA_SANTIAGO, TimeZone.AMERICA_SANTO_DOMINGO,
                  TimeZone.AMERICA_ST_BARTHELEMY, TimeZone.AMERICA_ST_KITTS, TimeZone.AMERICA_ST_LUCIA,
                  TimeZone.AMERICA_ST_THOMAS, TimeZone.AMERICA_ST_VINCENT, TimeZone.AMERICA_THULE,
                  TimeZone.AMERICA_TORTOLA, TimeZone.AMERICA_VIRGIN, TimeZone.ANTARCTICA_PALMER,
                  TimeZone.ATLANTIC_BERMUDA, TimeZone.ATLANTIC_STANLEY, TimeZone.BRAZIL_WEST, TimeZone.CANADA_ATLANTIC,
                  TimeZone.CHILE_CONTINENTAL, TimeZone.ETC_GMT4, TimeZone.PRT, TimeZone.SYSTEMV_AST4,
                  TimeZone.SYSTEMV_AST4ADT, TimeZone.AMERICA_ST_JOHNS, TimeZone.CNT, TimeZone.CANADA_NEWFOUNDLAND,
                  TimeZone.AGT, TimeZone.AMERICA_ARAGUAINA, TimeZone.AMERICA_ARGENTINA_BUENOS_AIRES,
                  TimeZone.AMERICA_ARGENTINA_CATAMARCA, TimeZone.AMERICA_ARGENTINA_COMODRIVADAVIA,
                  TimeZone.AMERICA_ARGENTINA_CORDOBA, TimeZone.AMERICA_ARGENTINA_JUJUY,
                  TimeZone.AMERICA_ARGENTINA_LA_RIOJA, TimeZone.AMERICA_ARGENTINA_MENDOZA,
                  TimeZone.AMERICA_ARGENTINA_RIO_GALLEGOS, TimeZone.AMERICA_ARGENTINA_SAN_JUAN,
                  TimeZone.AMERICA_ARGENTINA_SAN_LUIS, TimeZone.AMERICA_ARGENTINA_TUCUMAN,
                  TimeZone.AMERICA_ARGENTINA_USHUAIA, TimeZone.AMERICA_BAHIA, TimeZone.AMERICA_BELEM,
                  TimeZone.AMERICA_BUENOS_AIRES, TimeZone.AMERICA_CATAMARCA, TimeZone.AMERICA_CAYENNE,
                  TimeZone.AMERICA_CORDOBA, TimeZone.AMERICA_FORTALEZA, TimeZone.AMERICA_GODTHAB,
                  TimeZone.AMERICA_JUJUY, TimeZone.AMERICA_MACEIO, TimeZone.AMERICA_MENDOZA, TimeZone.AMERICA_MIQUELON,
                  TimeZone.AMERICA_MONTEVIDEO, TimeZone.AMERICA_PARAMARIBO, TimeZone.AMERICA_RECIFE,
                  TimeZone.AMERICA_ROSARIO, TimeZone.AMERICA_SAO_PAULO, TimeZone.ANTARCTICA_ROTHERA, TimeZone.BET,
                  TimeZone.BRAZIL_EAST, TimeZone.ETC_GMT3, TimeZone.AMERICA_NORONHA, TimeZone.ATLANTIC_SOUTH_GEORGIA,
                  TimeZone.BRAZIL_DENORONHA, TimeZone.ETC_GMT2, TimeZone.AMERICA_SCORESBYSUND, TimeZone.ATLANTIC_AZORES,
                  TimeZone.ATLANTIC_CAPE_VERDE, TimeZone.ETC_GMT1, TimeZone.AFRICA_ABIDJAN, TimeZone.AFRICA_ACCRA,
                  TimeZone.AFRICA_BAMAKO, TimeZone.AFRICA_BANJUL, TimeZone.AFRICA_BISSAU, TimeZone.AFRICA_CASABLANCA,
                  TimeZone.AFRICA_CONAKRY, TimeZone.AFRICA_DAKAR, TimeZone.AFRICA_EL_AAIUN, TimeZone.AFRICA_FREETOWN,
                  TimeZone.AFRICA_LOME, TimeZone.AFRICA_MONROVIA, TimeZone.AFRICA_NOUAKCHOTT,
                  TimeZone.AFRICA_OUAGADOUGOU, TimeZone.AFRICA_SAO_TOME, TimeZone.AFRICA_TIMBUKTU,
                  TimeZone.AMERICA_DANMARKSHAVN, TimeZone.ATLANTIC_CANARY, TimeZone.ATLANTIC_FAEROE,
                  TimeZone.ATLANTIC_FAROE, TimeZone.ATLANTIC_MADEIRA, TimeZone.ATLANTIC_REYKJAVIK,
                  TimeZone.ATLANTIC_ST_HELENA, TimeZone.EIRE, TimeZone.ETC_GMT, TimeZone.ETC_GMT_0, TimeZone.ETC_GMT0,
                  TimeZone.ETC_GREENWICH, TimeZone.ETC_UCT, TimeZone.ETC_UTC, TimeZone.ETC_UNIVERSAL, TimeZone.ETC_ZULU,
                  TimeZone.EUROPE_BELFAST, TimeZone.EUROPE_DUBLIN, TimeZone.EUROPE_GUERNSEY,
                  TimeZone.EUROPE_ISLE_OF_MAN, TimeZone.EUROPE_JERSEY, TimeZone.EUROPE_LISBON, TimeZone.EUROPE_LONDON,
                  TimeZone.GB, TimeZone.GB_EIRE, TimeZone.GMT, TimeZone.GMT0, TimeZone.GREENWICH, TimeZone.ICELAND,
                  TimeZone.PORTUGAL, TimeZone.UCT, TimeZone.UTC, TimeZone.UNIVERSAL, TimeZone.WET, TimeZone.ZULU,
                  TimeZone.AFRICA_ALGIERS, TimeZone.AFRICA_BANGUI, TimeZone.AFRICA_BRAZZAVILLE, TimeZone.AFRICA_CEUTA,
                  TimeZone.AFRICA_DOUALA, TimeZone.AFRICA_KINSHASA, TimeZone.AFRICA_LAGOS, TimeZone.AFRICA_LIBREVILLE,
                  TimeZone.AFRICA_LUANDA, TimeZone.AFRICA_MALABO, TimeZone.AFRICA_NDJAMENA, TimeZone.AFRICA_NIAMEY,
                  TimeZone.AFRICA_PORTO_NOVO, TimeZone.AFRICA_TUNIS, TimeZone.AFRICA_WINDHOEK,
                  TimeZone.ARCTIC_LONGYEARBYEN, TimeZone.ATLANTIC_JAN_MAYEN, TimeZone.CET, TimeZone.ECT,
                  TimeZone.ETC_GMT_1, TimeZone.EUROPE_AMSTERDAM, TimeZone.EUROPE_ANDORRA, TimeZone.EUROPE_BELGRADE,
                  TimeZone.EUROPE_BERLIN, TimeZone.EUROPE_BRATISLAVA, TimeZone.EUROPE_BRUSSELS,
                  TimeZone.EUROPE_BUDAPEST, TimeZone.EUROPE_COPENHAGEN, TimeZone.EUROPE_GIBRALTAR,
                  TimeZone.EUROPE_LJUBLJANA, TimeZone.EUROPE_LUXEMBOURG, TimeZone.EUROPE_MADRID, TimeZone.EUROPE_MALTA,
                  TimeZone.EUROPE_MONACO, TimeZone.EUROPE_OSLO, TimeZone.EUROPE_PARIS, TimeZone.EUROPE_PODGORICA,
                  TimeZone.EUROPE_PRAGUE, TimeZone.EUROPE_ROME, TimeZone.EUROPE_SAN_MARINO, TimeZone.EUROPE_SARAJEVO,
                  TimeZone.EUROPE_SKOPJE, TimeZone.EUROPE_STOCKHOLM, TimeZone.EUROPE_TIRANE, TimeZone.EUROPE_VADUZ,
                  TimeZone.EUROPE_VATICAN, TimeZone.EUROPE_VIENNA, TimeZone.EUROPE_WARSAW, TimeZone.EUROPE_ZAGREB,
                  TimeZone.EUROPE_ZURICH, TimeZone.MET, TimeZone.POLAND, TimeZone.ART, TimeZone.AFRICA_BLANTYRE,
                  TimeZone.AFRICA_BUJUMBURA, TimeZone.AFRICA_CAIRO, TimeZone.AFRICA_GABORONE, TimeZone.AFRICA_HARARE,
                  TimeZone.AFRICA_JOHANNESBURG, TimeZone.AFRICA_KIGALI, TimeZone.AFRICA_LUBUMBASHI,
                  TimeZone.AFRICA_LUSAKA, TimeZone.AFRICA_MAPUTO, TimeZone.AFRICA_MASERU, TimeZone.AFRICA_MBABANE,
                  TimeZone.AFRICA_TRIPOLI, TimeZone.ASIA_AMMAN, TimeZone.ASIA_BEIRUT, TimeZone.ASIA_DAMASCUS,
                  TimeZone.ASIA_GAZA, TimeZone.ASIA_ISTANBUL, TimeZone.ASIA_JERUSALEM, TimeZone.ASIA_NICOSIA,
                  TimeZone.ASIA_TEL_AVIV, TimeZone.CAT, TimeZone.EET, TimeZone.EGYPT, TimeZone.ETC_GMT_2,
                  TimeZone.EUROPE_ATHENS, TimeZone.EUROPE_BUCHAREST, TimeZone.EUROPE_CHISINAU, TimeZone.EUROPE_HELSINKI,
                  TimeZone.EUROPE_ISTANBUL, TimeZone.EUROPE_KALININGRAD, TimeZone.EUROPE_KIEV,
                  TimeZone.EUROPE_MARIEHAMN, TimeZone.EUROPE_MINSK, TimeZone.EUROPE_NICOSIA, TimeZone.EUROPE_RIGA,
                  TimeZone.EUROPE_SIMFEROPOL, TimeZone.EUROPE_SOFIA, TimeZone.EUROPE_TALLINN, TimeZone.EUROPE_TIRASPOL,
                  TimeZone.EUROPE_UZHGOROD, TimeZone.EUROPE_VILNIUS, TimeZone.EUROPE_ZAPOROZHYE, TimeZone.ISRAEL,
                  TimeZone.LIBYA, TimeZone.TURKEY, TimeZone.AFRICA_ADDIS_ABABA, TimeZone.AFRICA_ASMARA,
                  TimeZone.AFRICA_ASMERA, TimeZone.AFRICA_DAR_ES_SALAAM, TimeZone.AFRICA_DJIBOUTI,
                  TimeZone.AFRICA_KAMPALA, TimeZone.AFRICA_KHARTOUM, TimeZone.AFRICA_MOGADISHU, TimeZone.AFRICA_NAIROBI,
                  TimeZone.ANTARCTICA_SYOWA, TimeZone.ASIA_ADEN, TimeZone.ASIA_BAGHDAD, TimeZone.ASIA_BAHRAIN,
                  TimeZone.ASIA_KUWAIT, TimeZone.ASIA_QATAR, TimeZone.ASIA_RIYADH, TimeZone.EAT, TimeZone.ETC_GMT_3,
                  TimeZone.EUROPE_MOSCOW, TimeZone.EUROPE_VOLGOGRAD, TimeZone.INDIAN_ANTANANARIVO,
                  TimeZone.INDIAN_COMORO, TimeZone.INDIAN_MAYOTTE, TimeZone.W_SU, TimeZone.ASIA_RIYADH87,
                  TimeZone.ASIA_RIYADH88, TimeZone.ASIA_RIYADH89, TimeZone.MIDEAST_RIYADH87, TimeZone.MIDEAST_RIYADH88,
                  TimeZone.MIDEAST_RIYADH89, TimeZone.ASIA_TEHRAN, TimeZone.IRAN, TimeZone.ASIA_BAKU,
                  TimeZone.ASIA_DUBAI, TimeZone.ASIA_MUSCAT, TimeZone.ASIA_TBILISI, TimeZone.ASIA_YEREVAN,
                  TimeZone.ETC_GMT_4, TimeZone.EUROPE_SAMARA, TimeZone.INDIAN_MAHE, TimeZone.INDIAN_MAURITIUS,
                  TimeZone.INDIAN_REUNION, TimeZone.NET, TimeZone.ASIA_KABUL, TimeZone.ASIA_AQTAU, TimeZone.ASIA_AQTOBE,
                  TimeZone.ASIA_ASHGABAT, TimeZone.ASIA_ASHKHABAD, TimeZone.ASIA_DUSHANBE, TimeZone.ASIA_KARACHI,
                  TimeZone.ASIA_ORAL, TimeZone.ASIA_SAMARKAND, TimeZone.ASIA_TASHKENT, TimeZone.ASIA_YEKATERINBURG,
                  TimeZone.ETC_GMT_5, TimeZone.INDIAN_KERGUELEN, TimeZone.INDIAN_MALDIVES, TimeZone.PLT,
                  TimeZone.ASIA_CALCUTTA, TimeZone.ASIA_COLOMBO, TimeZone.ASIA_KOLKATA, TimeZone.IST,
                  TimeZone.ASIA_KATMANDU, TimeZone.ANTARCTICA_MAWSON, TimeZone.ANTARCTICA_VOSTOK, TimeZone.ASIA_ALMATY,
                  TimeZone.ASIA_BISHKEK, TimeZone.ASIA_DACCA, TimeZone.ASIA_DHAKA, TimeZone.ASIA_NOVOSIBIRSK,
                  TimeZone.ASIA_OMSK, TimeZone.ASIA_QYZYLORDA, TimeZone.ASIA_THIMBU, TimeZone.ASIA_THIMPHU,
                  TimeZone.BST, TimeZone.ETC_GMT_6, TimeZone.INDIAN_CHAGOS, TimeZone.ASIA_RANGOON,
                  TimeZone.INDIAN_COCOS, TimeZone.ANTARCTICA_DAVIS, TimeZone.ASIA_BANGKOK, TimeZone.ASIA_HO_CHI_MINH,
                  TimeZone.ASIA_HOVD, TimeZone.ASIA_JAKARTA, TimeZone.ASIA_KRASNOYARSK, TimeZone.ASIA_PHNOM_PENH,
                  TimeZone.ASIA_PONTIANAK, TimeZone.ASIA_SAIGON, TimeZone.ASIA_VIENTIANE, TimeZone.ETC_GMT_7,
                  TimeZone.INDIAN_CHRISTMAS, TimeZone.VST, TimeZone.ANTARCTICA_CASEY, TimeZone.ASIA_BRUNEI,
                  TimeZone.ASIA_CHOIBALSAN, TimeZone.ASIA_CHONGQING, TimeZone.ASIA_CHUNGKING, TimeZone.ASIA_HARBIN,
                  TimeZone.ASIA_HONG_KONG, TimeZone.ASIA_IRKUTSK, TimeZone.ASIA_KASHGAR, TimeZone.ASIA_KUALA_LUMPUR,
                  TimeZone.ASIA_KUCHING, TimeZone.ASIA_MACAO, TimeZone.ASIA_MACAU, TimeZone.ASIA_MAKASSAR,
                  TimeZone.ASIA_MANILA, TimeZone.ASIA_SHANGHAI, TimeZone.ASIA_SINGAPORE, TimeZone.ASIA_TAIPEI,
                  TimeZone.ASIA_UJUNG_PANDANG, TimeZone.ASIA_ULAANBAATAR, TimeZone.ASIA_ULAN_BATOR,
                  TimeZone.ASIA_URUMQI, TimeZone.AUSTRALIA_PERTH, TimeZone.AUSTRALIA_WEST, TimeZone.CTT,
                  TimeZone.ETC_GMT_8, TimeZone.HONGKONG, TimeZone.PRC, TimeZone.SINGAPORE, TimeZone.AUSTRALIA_EUCLA,
                  TimeZone.ASIA_DILI, TimeZone.ASIA_JAYAPURA, TimeZone.ASIA_PYONGYANG, TimeZone.ASIA_SEOUL,
                  TimeZone.ASIA_TOKYO, TimeZone.ASIA_YAKUTSK, TimeZone.ETC_GMT_9, TimeZone.JST, TimeZone.JAPAN,
                  TimeZone.PACIFIC_PALAU, TimeZone.ROK, TimeZone.ACT, TimeZone.AUSTRALIA_ADELAIDE,
                  TimeZone.AUSTRALIA_BROKEN_HILL, TimeZone.AUSTRALIA_DARWIN, TimeZone.AUSTRALIA_NORTH,
                  TimeZone.AUSTRALIA_SOUTH, TimeZone.AUSTRALIA_YANCOWINNA, TimeZone.AET,
                  TimeZone.ANTARCTICA_DUMONTDURVILLE, TimeZone.ASIA_SAKHALIN, TimeZone.ASIA_VLADIVOSTOK,
                  TimeZone.AUSTRALIA_ACT, TimeZone.AUSTRALIA_BRISBANE, TimeZone.AUSTRALIA_CANBERRA,
                  TimeZone.AUSTRALIA_CURRIE, TimeZone.AUSTRALIA_HOBART, TimeZone.AUSTRALIA_LINDEMAN,
                  TimeZone.AUSTRALIA_MELBOURNE, TimeZone.AUSTRALIA_NSW, TimeZone.AUSTRALIA_QUEENSLAND,
                  TimeZone.AUSTRALIA_SYDNEY, TimeZone.AUSTRALIA_TASMANIA, TimeZone.AUSTRALIA_VICTORIA,
                  TimeZone.ETC_GMT_10, TimeZone.PACIFIC_GUAM, TimeZone.PACIFIC_PORT_MORESBY, TimeZone.PACIFIC_SAIPAN,
                  TimeZone.PACIFIC_TRUK, TimeZone.PACIFIC_YAP, TimeZone.AUSTRALIA_LHI, TimeZone.AUSTRALIA_LORD_HOWE,
                  TimeZone.ASIA_MAGADAN, TimeZone.ETC_GMT_11, TimeZone.PACIFIC_EFATE, TimeZone.PACIFIC_GUADALCANAL,
                  TimeZone.PACIFIC_KOSRAE, TimeZone.PACIFIC_NOUMEA, TimeZone.PACIFIC_PONAPE, TimeZone.SST,
                  TimeZone.PACIFIC_NORFOLK, TimeZone.ANTARCTICA_MCMURDO, TimeZone.ANTARCTICA_SOUTH_POLE,
                  TimeZone.ASIA_ANADYR, TimeZone.ASIA_KAMCHATKA, TimeZone.ETC_GMT_12, TimeZone.KWAJALEIN, TimeZone.NST,
                  TimeZone.NZ, TimeZone.PACIFIC_AUCKLAND, TimeZone.PACIFIC_FIJI, TimeZone.PACIFIC_FUNAFUTI,
                  TimeZone.PACIFIC_KWAJALEIN, TimeZone.PACIFIC_MAJURO, TimeZone.PACIFIC_NAURU, TimeZone.PACIFIC_TARAWA,
                  TimeZone.PACIFIC_WAKE, TimeZone.PACIFIC_WALLIS, TimeZone.NZ_CHAT, TimeZone.PACIFIC_CHATHAM,
                  TimeZone.ETC_GMT_13, TimeZone.PACIFIC_ENDERBURY, TimeZone.PACIFIC_TONGATAPU, TimeZone.ETC_GMT_14,
                  TimeZone.PACIFIC_KIRITIMATI);
  public static final List<String> javaZones = Arrays
          .asList("Etc/GMT+12", "Etc/GMT+11", "MIT", "Pacific/Apia", "Pacific/Midway", "Pacific/Niue",
                  "Pacific/Pago_Pago", "Pacific/Samoa", "US/Samoa", "America/Adak", "America/Atka", "Etc/GMT+10", "HST",
                  "Pacific/Fakaofo", "Pacific/Honolulu", "Pacific/Johnston", "Pacific/Rarotonga", "Pacific/Tahiti",
                  "SystemV/HST10", "US/Aleutian", "US/Hawaii", "Pacific/Marquesas", "AST", "America/Anchorage",
                  "America/Juneau", "America/Nome", "America/Yakutat", "Etc/GMT+9", "Pacific/Gambier", "SystemV/YST9",
                  "SystemV/YST9YDT", "US/Alaska", "America/Dawson", "America/Ensenada", "America/Los_Angeles",
                  "America/Tijuana", "America/Vancouver", "America/Whitehorse", "Canada/Pacific", "Canada/Yukon",
                  "Etc/GMT+8", "Mexico/BajaNorte", "PST", "PST8PDT", "Pacific/Pitcairn", "SystemV/PST8",
                  "SystemV/PST8PDT", "US/Pacific", "US/Pacific-New", "America/Boise", "America/Cambridge_Bay",
                  "America/Chihuahua", "America/Dawson_Creek", "America/Denver", "America/Edmonton",
                  "America/Hermosillo", "America/Inuvik", "America/Mazatlan", "America/Phoenix", "America/Shiprock",
                  "America/Yellowknife", "Canada/Mountain", "Etc/GMT+7", "MST", "MST7MDT", "Mexico/BajaSur", "Navajo",
                  "PNT", "SystemV/MST7", "SystemV/MST7MDT", "US/Arizona", "US/Mountain", "America/Belize",
                  "America/Cancun", "America/Chicago", "America/Costa_Rica", "America/El_Salvador", "America/Guatemala",
                  "America/Indiana/Knox", "America/Indiana/Tell_City", "America/Knox_IN", "America/Managua",
                  "America/Menominee", "America/Merida", "America/Mexico_City", "America/Monterrey",
                  "America/North_Dakota/Center", "America/North_Dakota/New_Salem", "America/Rainy_River",
                  "America/Rankin_Inlet", "America/Regina", "America/Swift_Current", "America/Tegucigalpa",
                  "America/Winnipeg", "CST", "CST6CDT", "Canada/Central", "Canada/East-Saskatchewan",
                  "Canada/Saskatchewan", "Chile/EasterIsland", "Etc/GMT+6", "Mexico/General", "Pacific/Easter",
                  "Pacific/Galapagos", "SystemV/CST6", "SystemV/CST6CDT", "US/Central", "US/Indiana-Starke",
                  "America/Atikokan", "America/Bogota", "America/Cayman", "America/Coral_Harbour", "America/Detroit",
                  "America/Eirunepe", "America/Fort_Wayne", "America/Grand_Turk", "America/Guayaquil", "America/Havana",
                  "America/Indiana/Indianapolis", "America/Indiana/Marengo", "America/Indiana/Petersburg",
                  "America/Indiana/Vevay", "America/Indiana/Vincennes", "America/Indiana/Winamac",
                  "America/Indianapolis", "America/Iqaluit", "America/Jamaica", "America/Kentucky/Louisville",
                  "America/Kentucky/Monticello", "America/Lima", "America/Louisville", "America/Montreal",
                  "America/Nassau", "America/New_York", "America/Nipigon", "America/Panama", "America/Pangnirtung",
                  "America/Port-au-Prince", "America/Porto_Acre", "America/Resolute", "America/Rio_Branco",
                  "America/Thunder_Bay", "America/Toronto", "Brazil/Acre", "Canada/Eastern", "Cuba", "EST", "EST5EDT",
                  "Etc/GMT+5", "IET", "Jamaica", "SystemV/EST5", "SystemV/EST5EDT", "US/East-Indiana", "US/Eastern",
                  "US/Michigan", "America/Caracas", "America/Anguilla", "America/Antigua", "America/Aruba",
                  "America/Asuncion", "America/Barbados", "America/Blanc-Sablon", "America/Boa_Vista",
                  "America/Campo_Grande", "America/Cuiaba", "America/Curacao", "America/Dominica", "America/Glace_Bay",
                  "America/Goose_Bay", "America/Grenada", "America/Guadeloupe", "America/Guyana", "America/Halifax",
                  "America/La_Paz", "America/Manaus", "America/Marigot", "America/Martinique", "America/Moncton",
                  "America/Montserrat", "America/Port_of_Spain", "America/Porto_Velho", "America/Puerto_Rico",
                  "America/Santiago", "America/Santo_Domingo", "America/St_Barthelemy", "America/St_Kitts",
                  "America/St_Lucia", "America/St_Thomas", "America/St_Vincent", "America/Thule", "America/Tortola",
                  "America/Virgin", "Antarctica/Palmer", "Atlantic/Bermuda", "Atlantic/Stanley", "Brazil/West",
                  "Canada/Atlantic", "Chile/Continental", "Etc/GMT+4", "PRT", "SystemV/AST4", "SystemV/AST4ADT",
                  "America/St_Johns", "CNT", "Canada/Newfoundland", "AGT", "America/Araguaina",
                  "America/Argentina/Buenos_Aires", "America/Argentina/Catamarca", "America/Argentina/ComodRivadavia",
                  "America/Argentina/Cordoba", "America/Argentina/Jujuy", "America/Argentina/La_Rioja",
                  "America/Argentina/Mendoza", "America/Argentina/Rio_Gallegos", "America/Argentina/San_Juan",
                  "America/Argentina/San_Luis", "America/Argentina/Tucuman", "America/Argentina/Ushuaia",
                  "America/Bahia", "America/Belem", "America/Buenos_Aires", "America/Catamarca", "America/Cayenne",
                  "America/Cordoba", "America/Fortaleza", "America/Godthab", "America/Jujuy", "America/Maceio",
                  "America/Mendoza", "America/Miquelon", "America/Montevideo", "America/Paramaribo", "America/Recife",
                  "America/Rosario", "America/Sao_Paulo", "Antarctica/Rothera", "BET", "Brazil/East", "Etc/GMT+3",
                  "America/Noronha", "Atlantic/South_Georgia", "Brazil/DeNoronha", "Etc/GMT+2", "America/Scoresbysund",
                  "Atlantic/Azores", "Atlantic/Cape_Verde", "Etc/GMT+1", "Africa/Abidjan", "Africa/Accra",
                  "Africa/Bamako", "Africa/Banjul", "Africa/Bissau", "Africa/Casablanca", "Africa/Conakry",
                  "Africa/Dakar", "Africa/El_Aaiun", "Africa/Freetown", "Africa/Lome", "Africa/Monrovia",
                  "Africa/Nouakchott", "Africa/Ouagadougou", "Africa/Sao_Tome", "Africa/Timbuktu",
                  "America/Danmarkshavn", "Atlantic/Canary", "Atlantic/Faeroe", "Atlantic/Faroe", "Atlantic/Madeira",
                  "Atlantic/Reykjavik", "Atlantic/St_Helena", "Eire", "Etc/GMT", "Etc/GMT+0", "Etc/GMT-0",
                  "Etc/Greenwich", "Etc/UCT", "Etc/UTC", "Etc/Universal", "Etc/Zulu", "Europe/Belfast", "Europe/Dublin",
                  "Europe/Guernsey", "Europe/Isle_of_Man", "Europe/Jersey", "Europe/Lisbon", "Europe/London", "GB",
                  "GB-Eire", "GMT", "GMT0", "Greenwich", "Iceland", "Portugal", "UCT", "UTC", "Universal", "WET",
                  "Zulu", "Africa/Algiers", "Africa/Bangui", "Africa/Brazzaville", "Africa/Ceuta", "Africa/Douala",
                  "Africa/Kinshasa", "Africa/Lagos", "Africa/Libreville", "Africa/Luanda", "Africa/Malabo",
                  "Africa/Ndjamena", "Africa/Niamey", "Africa/Porto-Novo", "Africa/Tunis", "Africa/Windhoek",
                  "Arctic/Longyearbyen", "Atlantic/Jan_Mayen", "CET", "ECT", "Etc/GMT-1", "Europe/Amsterdam",
                  "Europe/Andorra", "Europe/Belgrade", "Europe/Berlin", "Europe/Bratislava", "Europe/Brussels",
                  "Europe/Budapest", "Europe/Copenhagen", "Europe/Gibraltar", "Europe/Ljubljana", "Europe/Luxembourg",
                  "Europe/Madrid", "Europe/Malta", "Europe/Monaco", "Europe/Oslo", "Europe/Paris", "Europe/Podgorica",
                  "Europe/Prague", "Europe/Rome", "Europe/San_Marino", "Europe/Sarajevo", "Europe/Skopje",
                  "Europe/Stockholm", "Europe/Tirane", "Europe/Vaduz", "Europe/Vatican", "Europe/Vienna",
                  "Europe/Warsaw", "Europe/Zagreb", "Europe/Zurich", "MET", "Poland", "ART", "Africa/Blantyre",
                  "Africa/Bujumbura", "Africa/Cairo", "Africa/Gaborone", "Africa/Harare", "Africa/Johannesburg",
                  "Africa/Kigali", "Africa/Lubumbashi", "Africa/Lusaka", "Africa/Maputo", "Africa/Maseru",
                  "Africa/Mbabane", "Africa/Tripoli", "Asia/Amman", "Asia/Beirut", "Asia/Damascus", "Asia/Gaza",
                  "Asia/Istanbul", "Asia/Jerusalem", "Asia/Nicosia", "Asia/Tel_Aviv", "CAT", "EET", "Egypt",
                  "Etc/GMT-2", "Europe/Athens", "Europe/Bucharest", "Europe/Chisinau", "Europe/Helsinki",
                  "Europe/Istanbul", "Europe/Kaliningrad", "Europe/Kiev", "Europe/Mariehamn", "Europe/Minsk",
                  "Europe/Nicosia", "Europe/Riga", "Europe/Simferopol", "Europe/Sofia", "Europe/Tallinn",
                  "Europe/Tiraspol", "Europe/Uzhgorod", "Europe/Vilnius", "Europe/Zaporozhye", "Israel", "Libya",
                  "Turkey", "Africa/Addis_Ababa", "Africa/Asmara", "Africa/Asmera", "Africa/Dar_es_Salaam",
                  "Africa/Djibouti", "Africa/Kampala", "Africa/Khartoum", "Africa/Mogadishu", "Africa/Nairobi",
                  "Antarctica/Syowa", "Asia/Aden", "Asia/Baghdad", "Asia/Bahrain", "Asia/Kuwait", "Asia/Qatar",
                  "Asia/Riyadh", "EAT", "Etc/GMT-3", "Europe/Moscow", "Europe/Volgograd", "Indian/Antananarivo",
                  "Indian/Comoro", "Indian/Mayotte", "W-SU", "Asia/Riyadh87", "Asia/Riyadh88", "Asia/Riyadh89",
                  "Mideast/Riyadh87", "Mideast/Riyadh88", "Mideast/Riyadh89", "Asia/Tehran", "Iran", "Asia/Baku",
                  "Asia/Dubai", "Asia/Muscat", "Asia/Tbilisi", "Asia/Yerevan", "Etc/GMT-4", "Europe/Samara",
                  "Indian/Mahe", "Indian/Mauritius", "Indian/Reunion", "NET", "Asia/Kabul", "Asia/Aqtau", "Asia/Aqtobe",
                  "Asia/Ashgabat", "Asia/Ashkhabad", "Asia/Dushanbe", "Asia/Karachi", "Asia/Oral", "Asia/Samarkand",
                  "Asia/Tashkent", "Asia/Yekaterinburg", "Etc/GMT-5", "Indian/Kerguelen", "Indian/Maldives", "PLT",
                  "Asia/Calcutta", "Asia/Colombo", "Asia/Kolkata", "IST", "Asia/Katmandu", "Antarctica/Mawson",
                  "Antarctica/Vostok", "Asia/Almaty", "Asia/Bishkek", "Asia/Dacca", "Asia/Dhaka", "Asia/Novosibirsk",
                  "Asia/Omsk", "Asia/Qyzylorda", "Asia/Thimbu", "Asia/Thimphu", "BST", "Etc/GMT-6", "Indian/Chagos",
                  "Asia/Rangoon", "Indian/Cocos", "Antarctica/Davis", "Asia/Bangkok", "Asia/Ho_Chi_Minh", "Asia/Hovd",
                  "Asia/Jakarta", "Asia/Krasnoyarsk", "Asia/Phnom_Penh", "Asia/Pontianak", "Asia/Saigon",
                  "Asia/Vientiane", "Etc/GMT-7", "Indian/Christmas", "VST", "Antarctica/Casey", "Asia/Brunei",
                  "Asia/Choibalsan", "Asia/Chongqing", "Asia/Chungking", "Asia/Harbin", "Asia/Hong_Kong",
                  "Asia/Irkutsk", "Asia/Kashgar", "Asia/Kuala_Lumpur", "Asia/Kuching", "Asia/Macao", "Asia/Macau",
                  "Asia/Makassar", "Asia/Manila", "Asia/Shanghai", "Asia/Singapore", "Asia/Taipei",
                  "Asia/Ujung_Pandang", "Asia/Ulaanbaatar", "Asia/Ulan_Bator", "Asia/Urumqi", "Australia/Perth",
                  "Australia/West", "CTT", "Etc/GMT-8", "Hongkong", "PRC", "Singapore", "Australia/Eucla", "Asia/Dili",
                  "Asia/Jayapura", "Asia/Pyongyang", "Asia/Seoul", "Asia/Tokyo", "Asia/Yakutsk", "Etc/GMT-9", "JST",
                  "Japan", "Pacific/Palau", "ROK", "ACT", "Australia/Adelaide", "Australia/Broken_Hill",
                  "Australia/Darwin", "Australia/North", "Australia/South", "Australia/Yancowinna", "AET",
                  "Antarctica/DumontDUrville", "Asia/Sakhalin", "Asia/Vladivostok", "Australia/ACT",
                  "Australia/Brisbane", "Australia/Canberra", "Australia/Currie", "Australia/Hobart",
                  "Australia/Lindeman", "Australia/Melbourne", "Australia/NSW", "Australia/Queensland",
                  "Australia/Sydney", "Australia/Tasmania", "Australia/Victoria", "Etc/GMT-10", "Pacific/Guam",
                  "Pacific/Port_Moresby", "Pacific/Saipan", "Pacific/Truk", "Pacific/Yap", "Australia/LHI",
                  "Australia/Lord_Howe", "Asia/Magadan", "Etc/GMT-11", "Pacific/Efate", "Pacific/Guadalcanal",
                  "Pacific/Kosrae", "Pacific/Noumea", "Pacific/Ponape", "SST", "Pacific/Norfolk", "Antarctica/McMurdo",
                  "Antarctica/South_Pole", "Asia/Anadyr", "Asia/Kamchatka", "Etc/GMT-12", "Kwajalein", "NST", "NZ",
                  "Pacific/Auckland", "Pacific/Fiji", "Pacific/Funafuti", "Pacific/Kwajalein", "Pacific/Majuro",
                  "Pacific/Nauru", "Pacific/Tarawa", "Pacific/Wake", "Pacific/Wallis", "NZ-CHAT", "Pacific/Chatham",
                  "Etc/GMT-13", "Pacific/Enderbury", "Pacific/Tongatapu", "Etc/GMT-14", "Pacific/Kiritimati");

	/**
	 * Gives a {@code TimeZone} for a given Java {@code java.util.TimeZone}
	 * Returns null if no time zone was found.
	 * @param timeZone - the Java time zone
	 * @return - time zone corresponding to the Java time zone or null
	 */
  public static TimeZone convert(java.util.TimeZone timeZone) {
    return zones.get(javaZones.indexOf(timeZone.getID()));
  }

	/**
	 * Gives a Java {@code java.util.TimeZone} for a given {@code TimeZone}
	 * Returns null if no time zone was found.
	 * @param timeZone - the enum time zone
	 * @return - Java time zone corresponding to the passed enum time zone or null
	 */
  public static java.util.TimeZone convert(TimeZone timeZone) {
    return java.util.TimeZone.getTimeZone(javaZones.get(zones.indexOf(timeZone))); 
  }
}
