
package eu.heliovo.dpas.ie.services.hqi.service.eu.helio_vo.xml.queryservice.v0_1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.10
 * Wed Sep 15 11:23:43 BST 2010
 * Generated source version: 2.2.10
 * 
 */

public final class HelioQueryService_HelioQueryServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://helio-vo.eu/xml/QueryService/v0.1", "HelioQueryServiceService");

    private HelioQueryService_HelioQueryServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = HelioQueryServiceService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HelioQueryServiceService ss = new HelioQueryServiceService(wsdlURL, SERVICE_NAME);
        HelioQueryService port = ss.getHelioQueryServicePort();  
        
        {
        System.out.println("Invoking timeQuery...");
        eu.heliovo.dpas.ie.services.hqi.service.eu.helio_vo.xml.queryservice.v0.TimeQuery _timeQuery_parameters = null;
        eu.heliovo.dpas.ie.services.hqi.service.eu.helio_vo.xml.queryservice.v0.QueryResponse _timeQuery__return = port.timeQuery(_timeQuery_parameters);
        System.out.println("timeQuery.result=" + _timeQuery__return);


        }
        {
        System.out.println("Invoking query...");
        eu.heliovo.dpas.ie.services.hqi.service.eu.helio_vo.xml.queryservice.v0.Query _query_parameters = null;
        eu.heliovo.dpas.ie.services.hqi.service.eu.helio_vo.xml.queryservice.v0.QueryResponse _query__return = port.query(_query_parameters);
        System.out.println("query.result=" + _query__return);


        }

        System.exit(0);
    }

}
