
package eu.heliovo.workflow.clients.ics;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HelioQueryService", targetNamespace = "http://helio-vo.eu/xml/QueryService/v0.1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelioQueryService {


    /**
     * 
     * @param query
     * @return
     *     returns eu.heliovo.workflow.clients.ics.QueryResponse
     */
    @WebMethod(operationName = "Query")
    @WebResult(name = "queryResponse", targetNamespace = "http://helio-vo.eu/xml/QueryService/v0.1", partName = "response")
    public QueryResponse query(
        @WebParam(name = "Query", targetNamespace = "http://helio-vo.eu/xml/QueryService/v0.1", partName = "query")
        Query query);

    /**
     * 
     * @param timequery
     * @return
     *     returns eu.heliovo.workflow.clients.ics.QueryResponse
     */
    @WebMethod(operationName = "TimeQuery")
    @WebResult(name = "queryResponse", targetNamespace = "http://helio-vo.eu/xml/QueryService/v0.1", partName = "response")
    public QueryResponse timeQuery(
        @WebParam(name = "TimeQuery", targetNamespace = "http://helio-vo.eu/xml/QueryService/v0.1", partName = "timequery")
        TimeQuery timequery);

}
