
package eu.heliovo.dpas.ie.services.soda.service.eu.soteriaspace.wsdls.soteria;

import javax.xml.ws.WebFault;
import eu.heliovo.dpas.ie.services.soda.service.eu.soteriaspace.schemas.webservice.QueryError;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "error", targetNamespace = "http://soteriaspace.eu/schemas/webservice")
public class QueryFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private QueryError faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public QueryFault(String message, QueryError faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public QueryFault(String message, QueryError faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: eu.soteriaspace.schemas.webservice.QueryError
     */
    public QueryError getFaultInfo() {
        return faultInfo;
    }

}
