
package eu.heliovo.dpas.ie.services.soda.service.eu.soteriaspace.wsdls.soteria;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import eu.heliovo.dpas.ie.services.soda.service.eu.soteriaspace.schemas.details.RecordDetail;
import eu.heliovo.dpas.ie.services.soda.service.eu.soteriaspace.schemas.webservice.GetRecordDetailsRequest;
import eu.heliovo.dpas.ie.services.soda.service.eu.soteriaspace.schemas.webservice.QueryRequest;
import eu.heliovo.dpas.ie.services.soda.service.eu.soteriaspace.schemas.webservice.QueryResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "soteriaPort", targetNamespace = "http://soteriaspace.eu/wsdls/soteria")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
	eu.heliovo.dpas.ie.services.soda.service.eu.soteriaspace.schemas.webservice.ObjectFactory.class,
	eu.heliovo.dpas.ie.services.soda.service.eu.soteriaspace.schemas.details.ObjectFactory.class,
	eu.heliovo.dpas.ie.services.soda.service.eu.soteriaspace.schemas.datasets.ObjectFactory.class,
	eu.heliovo.dpas.ie.services.soda.service.eu.soteriaspace.schemas.query.ObjectFactory.class
})
public interface SoteriaPort {


    /**
     * 
     * @param request
     * @return
     *     returns eu.soteriaspace.schemas.webservice.QueryResponse
     * @throws QueryFault
     */
    @WebMethod
    @WebResult(name = "queryResponse", targetNamespace = "http://soteriaspace.eu/schemas/webservice", partName = "response")
    public QueryResponse query(
        @WebParam(name = "queryRequest", targetNamespace = "http://soteriaspace.eu/schemas/webservice", partName = "request")
        QueryRequest request)
        throws QueryFault
    ;

    /**
     * 
     * @param request
     * @return
     *     returns eu.soteriaspace.schemas.details.RecordDetail
     * @throws QueryFault
     */
    @WebMethod
    @WebResult(name = "recordDetail", targetNamespace = "http://soteriaspace.eu/schemas/details", partName = "response")
    public RecordDetail detail(
        @WebParam(name = "getRecordDetailsRequest", targetNamespace = "http://soteriaspace.eu/schemas/webservice", partName = "request")
        GetRecordDetailsRequest request)
        throws QueryFault
    ;

}
