// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.egso.comms.nds.types;


public class ApplicationList {
    protected org.egso.comms.nds.types.Application[] applications;
    
    public ApplicationList() {
    }
    
    public ApplicationList(org.egso.comms.nds.types.Application[] applications) {
        this.applications = applications;
    }
    
    public org.egso.comms.nds.types.Application[] getApplications() {
        return applications;
    }
    
    public void setApplications(org.egso.comms.nds.types.Application[] applications) {
        this.applications = applications;
    }
}
