// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.egso.comms.nds.types;


public class PIS {
    protected java.lang.String id;
    protected java.lang.String name;
    protected java.net.URI endpoint;
    protected boolean alive;
    
    public PIS() {
    }
    
    public PIS(java.lang.String id, java.lang.String name, java.net.URI endpoint, boolean alive) {
        this.id = id;
        this.name = name;
        this.endpoint = endpoint;
        this.alive = alive;
    }
    
    public java.lang.String getId() {
        return id;
    }
    
    public void setId(java.lang.String id) {
        this.id = id;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public java.net.URI getEndpoint() {
        return endpoint;
    }
    
    public void setEndpoint(java.net.URI endpoint) {
        this.endpoint = endpoint;
    }
    
    public boolean isAlive() {
        return alive;
    }
    
    public void setAlive(boolean alive) {
        this.alive = alive;
    }
}
