// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.egso.comms.nds.types;

import java.util.ArrayList;
import java.util.List;

import javax.xml.namespace.QName;

import com.sun.xml.rpc.encoding.CombinedSerializer;
import com.sun.xml.rpc.encoding.DeserializationException;
import com.sun.xml.rpc.encoding.Initializable;
import com.sun.xml.rpc.encoding.InternalTypeMappingRegistry;
import com.sun.xml.rpc.encoding.SOAPDeserializationContext;
import com.sun.xml.rpc.encoding.SOAPSerializationContext;
import com.sun.xml.rpc.encoding.literal.LiteralObjectSerializerBase;
import com.sun.xml.rpc.streaming.XMLReader;
import com.sun.xml.rpc.streaming.XMLReaderUtil;
import com.sun.xml.rpc.streaming.XMLWriter;

public class PISList_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final QName ns1_pis_QNAME = new QName("", "pis");
    private static final QName ns3_PIS_TYPE_QNAME = new QName("urn:org.egso.comms/nds/types/", "PIS");
    private CombinedSerializer ns3_myPIS_LiteralSerializer;
    
    public PISList_LiteralSerializer(QName type, String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public PISList_LiteralSerializer(QName type, String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns3_myPIS_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", org.egso.comms.nds.types.PIS.class, ns3_PIS_TYPE_QNAME);
    }
    
    public Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws Exception {
        org.egso.comms.nds.types.PISList instance = new org.egso.comms.nds.types.PISList();
        Object member=null;
        QName elementName;
        List values;
        Object value;
        
        reader.nextElementContent();
        elementName = reader.getName();
        if ((reader.getState() == XMLReader.START) && (elementName.equals(ns1_pis_QNAME))) {
            values = new ArrayList();
            for(;;) {
                elementName = reader.getName();
                if ((reader.getState() == XMLReader.START) && (elementName.equals(ns1_pis_QNAME))) {
                    value = ns3_myPIS_LiteralSerializer.deserialize(ns1_pis_QNAME, reader, context);
                    if (value == null) {
                        throw new DeserializationException("literal.unexpectedNull");
                    }
                    values.add(value);
                    reader.nextElementContent();
                } else {
                    break;
                }
            }
            member = new org.egso.comms.nds.types.PIS[values.size()];
            member = values.toArray((Object[]) member);
            instance.setPis((org.egso.comms.nds.types.PIS[])member);
        }
        else {
            instance.setPis(new org.egso.comms.nds.types.PIS[0]);
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (Object)instance;
    }
    
    public void doSerializeAttributes(Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        org.egso.comms.nds.types.PISList instance = (org.egso.comms.nds.types.PISList)obj;
        
    }
    public void doSerialize(Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        org.egso.comms.nds.types.PISList instance = (org.egso.comms.nds.types.PISList)obj;
        
        if (instance.getPis() != null) {
            for (int i = 0; i < instance.getPis().length; ++i) {
                ns3_myPIS_LiteralSerializer.serialize(instance.getPis()[i], ns1_pis_QNAME, null, writer, context);
            }
        }
    }
}
