// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.egso.comms.nds.types;


public class PISList {
    protected org.egso.comms.nds.types.PIS[] pis;
    
    public PISList() {
    }
    
    public PISList(org.egso.comms.nds.types.PIS[] pis) {
        this.pis = pis;
    }
    
    public org.egso.comms.nds.types.PIS[] getPis() {
        return pis;
    }
    
    public void setPis(org.egso.comms.nds.types.PIS[] pis) {
        this.pis = pis;
    }
}
