// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.egso.comms.nds.wsdl;

public interface NDS_PortType extends java.rmi.Remote {
    public org.egso.comms.nds.types.PIS registerPIS(org.egso.comms.nds.types.PIS pis) throws 
         java.rmi.RemoteException;
    public void updatePIS(org.egso.comms.nds.types.PIS pis) throws 
         java.rmi.RemoteException;
    public void deregisterPIS(org.egso.comms.nds.types.PIS pis) throws 
         java.rmi.RemoteException;
    public org.egso.comms.nds.types.PIS selectPISById(java.lang.String id) throws 
         java.rmi.RemoteException;
    public org.egso.comms.nds.types.PISList selectPISByName(java.lang.String name) throws 
         java.rmi.RemoteException;
    public org.egso.comms.nds.types.PISList selectPISByEndpoint(java.net.URI endpoint) throws 
         java.rmi.RemoteException;
    public org.egso.comms.nds.types.PISList selectPISByAlive(boolean alive) throws 
         java.rmi.RemoteException;
    public org.egso.comms.nds.types.PISList selectPISByApplicationId(java.lang.String applicationId) throws 
         java.rmi.RemoteException;
    public org.egso.comms.nds.types.Application registerApplication(org.egso.comms.nds.types.Application application) throws 
         java.rmi.RemoteException;
    public void updateApplication(org.egso.comms.nds.types.Application application) throws 
         java.rmi.RemoteException;
    public void deregisterApplication(org.egso.comms.nds.types.Application application) throws 
         java.rmi.RemoteException;
    public org.egso.comms.nds.types.Application selectApplicationById(java.lang.String id) throws 
         java.rmi.RemoteException;
    public org.egso.comms.nds.types.ApplicationList selectApplicationsByParentPISId(java.lang.String parentPISId) throws 
         java.rmi.RemoteException;
    public org.egso.comms.nds.types.ApplicationList selectApplicationsByName(java.lang.String name) throws 
         java.rmi.RemoteException;
    public org.egso.comms.nds.types.ApplicationList selectApplicationsByType(java.net.URI type) throws 
         java.rmi.RemoteException;
    public org.egso.comms.nds.types.ApplicationList selectApplicationsByEndpoint(java.net.URI endpoint) throws 
         java.rmi.RemoteException;
    public org.egso.comms.nds.types.ApplicationList selectApplicationsByAlive(boolean alive) throws 
         java.rmi.RemoteException;
    public void synchronizeDirectory() throws 
         java.rmi.RemoteException;
}
