# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.cert.errors", 1);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1312381891);
user_pref("app.update.lastUpdateTime.background-update-timer", 1312381771);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1312375846);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1312382011);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1246352742);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1312375679);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 640000);
user_pref("browser.download.dir", "C:\\Users\\caschy\\Downloads");
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.feeds.handler", "bookmarks");
user_pref("browser.feeds.handler.default", "bookmarks");
user_pref("browser.feeds.showFirstRunUI", false);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.migration.version", 5);
user_pref("browser.panorama.experienced_first_run", true);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.rights.3.shown", true);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage", "http://stadt-bremerhaven.de/");
user_pref("browser.startup.homepage_override.buildID", "20110318052756");
user_pref("browser.startup.homepage_override.mstone", "rv:2.0");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.taskbar.lastgroupid", "Mozilla.Firefox.4.0");
user_pref("extensions.adblockplus.currentVersion", "1.3.9");
user_pref("extensions.blocklist.pingCount", -1);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 3);
user_pref("extensions.enabledAddons", "firebug@software.joehewitt.com:1.7.3,FireXPath@pierre.tholence.com:0.9.6.1,{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}:1.3.9,{972ce4c6-7e08-4474-a285-3208198ce6fd}:4.0");
user_pref("extensions.enabledItems", "{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.4");
user_pref("extensions.firebug.addonBarOpened", true);
user_pref("extensions.firebug.currentVersion", "1.7.3");
user_pref("extensions.firebug.defaultPanelName", "firepath");
user_pref("extensions.firebug.toolbarCustomizationDone", true);
user_pref("extensions.google.updater.{000a9d1c-beef-4f90-9363-039d445309b8}", "1238169855321");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"testpilot@labs.mozilla.com\":{\"descriptor\":\"D:\\\\FHNW\\\\Selenium\\\\portable\\\\ff4\\\\Portable_Firefox_4.0\\\\Firefox\\\\extensions\\\\testpilot@labs.mozilla.com\",\"mtime\":1288920173000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"D:\\\\FHNW\\\\Selenium\\\\portable\\\\ff4\\\\Portable_Firefox_4.0\\\\Firefox\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1300698775694}}},{\"name\":\"app-profile\",\"addons\":{\"firebug@software.joehewitt.com\":{\"descriptor\":\"D:\\\\FHNW\\\\Selenium\\\\portable\\\\ff4\\\\Portable_Firefox_4.0\\\\Profilordner\\\\extensions\\\\firebug@software.joehewitt.com.xpi\",\"mtime\":1312375725687},\"FireXPath@pierre.tholence.com\":{\"descriptor\":\"D:\\\\FHNW\\\\Selenium\\\\portable\\\\ff4\\\\Portable_Firefox_4.0\\\\Profilordner\\\\extensions\\\\FireXPath@pierre.tholence.com.xpi\",\"mtime\":1312375725696},\"{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\":{\"descriptor\":\"D:\\\\FHNW\\\\Selenium\\\\portable\\\\ff4\\\\Portable_Firefox_4.0\\\\Profilordner\\\\extensions\\\\{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}.xpi\",\"mtime\":1312375725705}}}]");
user_pref("extensions.installedDistroAddon.testpilot@labs.mozilla.com", true);
user_pref("extensions.lastAppVersion", "4.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.testpilot.dateForDataDeletion.12", "Sun Apr 10 2011 23:14:44 GMT+0200");
user_pref("extensions.testpilot.expirationDateForDataSubmission.12", "Sun Apr 10 2011 23:14:44 GMT+0200");
user_pref("extensions.testpilot.startDate.100", "Tue Jul 27 2010 20:47:26 GMT+0200");
user_pref("extensions.testpilot.startDate.101", "Fri Feb 25 2011 22:14:44 GMT+0100");
user_pref("extensions.testpilot.startDate.12", "Sun Mar 27 2011 23:14:44 GMT+0200");
user_pref("extensions.testpilot.startDate.7", "Tue Jul 06 2010 22:41:47 GMT+0200");
user_pref("extensions.testpilot.taskstatus.1", 9);
user_pref("extensions.testpilot.taskstatus.100", 9);
user_pref("extensions.testpilot.taskstatus.101", 9);
user_pref("extensions.testpilot.taskstatus.12", 4);
user_pref("extensions.testpilot.taskstatus.3", 9);
user_pref("extensions.testpilot.taskstatus.4", 9);
user_pref("extensions.testpilot.taskstatus.5", 9);
user_pref("extensions.testpilot.taskstatus.6", 9);
user_pref("extensions.testpilot.taskstatus.8", 9);
user_pref("extensions.testpilot.taskstatus.account_password_survey", 9);
user_pref("extensions.testpilot.taskstatus.basic_panel_survey_2", 3);
user_pref("extensions.testpilot.taskstatus.beta_perception_survey_1", 9);
user_pref("extensions.testpilot@labs.mozilla.com.install-event-fired", true);
user_pref("extensions.update.notifyUser", false);
user_pref("extensions.{3252b9ae-c69a-4eaf-9502-dc9c1f6c009e}.install-event-fired", true);
user_pref("general.useragent.extra.microsoftdotnet", "(.NET CLR 3.5.30729)");
user_pref("idle.lastDailyNotification", 1270190442);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("microsoft.CLR.auto_install", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 64360);
user_pref("places.last_vacuum", 1270190442);
user_pref("pref.privacy.disable_button.view_passwords", false);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("services.sync.lastversion", "1.7b1pre");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1314967561);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.103", "");
user_pref("xpinstall.whitelist.add.36", "");
