
package eu.helio_vo.xml.queryservice.v0;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import eu.helio_vo.xml.instruments.v0.Instrument;
import net.ivoa.xml.votable.v1.VOTABLE;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HelioQueryService", targetNamespace = "http://helio-vo.eu/xml/QueryService/v0.1")
@XmlSeeAlso({
    eu.helio_vo.xml.queryservice.v0.ObjectFactory.class,
    net.ivoa.xml.votable.v1.ObjectFactory.class,
    eu.helio_vo.xml.instruments.v0.ObjectFactory.class
})
public interface HelioQueryService {


    /**
     * 
     * @param endtime
     * @param maxrecords
     * @param startindex
     * @param starttime
     * @param instrument
     * @param from
     * @param where
     * @return
     *     returns net.ivoa.xml.votable.v1.VOTABLE
     */
    @WebMethod(operationName = "Query")
    @WebResult(name = "VOTABLE", targetNamespace = "http://www.ivoa.net/xml/VOTable/v1.1")
    @RequestWrapper(localName = "Query", targetNamespace = "http://helio-vo.eu/xml/QueryService/v0.1", className = "eu.helio_vo.xml.queryservice.v0.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://helio-vo.eu/xml/QueryService/v0.1", className = "eu.helio_vo.xml.queryservice.v0.QueryResponse")
    public VOTABLE query(
        @WebParam(name = "STARTTIME", targetNamespace = "")
        List<String> starttime,
        @WebParam(name = "ENDTIME", targetNamespace = "")
        List<String> endtime,
        @WebParam(name = "FROM", targetNamespace = "")
        List<String> from,
        @WebParam(name = "WHERE", targetNamespace = "")
        String where,
        @WebParam(name = "INSTRUMENT", targetNamespace = "")
        Instrument instrument,
        @WebParam(name = "MAXRECORDS", targetNamespace = "")
        Integer maxrecords,
        @WebParam(name = "STARTINDEX", targetNamespace = "")
        Integer startindex);

    /**
     * 
     * @param endtime
     * @param maxrecords
     * @param startindex
     * @param starttime
     * @param from
     * @return
     *     returns net.ivoa.xml.votable.v1.VOTABLE
     */
    @WebMethod(operationName = "TimeQuery")
    @WebResult(name = "VOTABLE", targetNamespace = "http://www.ivoa.net/xml/VOTable/v1.1")
    @RequestWrapper(localName = "TimeQuery", targetNamespace = "http://helio-vo.eu/xml/QueryService/v0.1", className = "eu.helio_vo.xml.queryservice.v0.TimeQuery")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://helio-vo.eu/xml/QueryService/v0.1", className = "eu.helio_vo.xml.queryservice.v0.QueryResponse")
    public VOTABLE timeQuery(
        @WebParam(name = "STARTTIME", targetNamespace = "")
        List<String> starttime,
        @WebParam(name = "ENDTIME", targetNamespace = "")
        List<String> endtime,
        @WebParam(name = "FROM", targetNamespace = "")
        List<String> from,
        @WebParam(name = "MAXRECORDS", targetNamespace = "")
        Integer maxrecords,
        @WebParam(name = "STARTINDEX", targetNamespace = "")
        Integer startindex);

}
