// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.egso.comms.eis.wsdl;

public interface Application_PortType extends java.rmi.Remote {
    public void receiveMessage(org.egso.comms.pis.types.Message message) throws 
         java.rmi.RemoteException;
    public void returnMessage(org.egso.comms.pis.types.Message message) throws 
         java.rmi.RemoteException;
}
